-- Artist-owned catalog distribution, rights audit trail, and DMCA intake.
-- Personal track_audio rows remain private. Public discovery is granted only
-- through a separately reviewed artist agreement and short-lived signed URLs.

create table if not exists jukebox.artist_rights_agreements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  artist_id uuid not null references jukebox.artists(id) on delete restrict,
  user_email text not null,
  legal_name text not null,
  stage_name text not null,
  organization text,
  authority_role text not null,
  country text not null,
  website text,
  contact_phone text,
  catalog_description text,
  owns_sound_recordings boolean not null,
  controls_compositions boolean not null,
  cleared_contributors boolean not null,
  cleared_samples boolean not null,
  cleared_artwork boolean not null,
  original_catalog_only boolean not null,
  grant_confirmed boolean not null,
  dmca_confirmed boolean not null,
  accurate_information_confirmed boolean not null,
  agreement_version text not null,
  agreement_sha256 text not null,
  agreement_snapshot jsonb not null,
  signed_name text not null,
  signed_at timestamptz not null default now(),
  signature_ip inet,
  signature_user_agent text,
  status text not null default 'pending',
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint artist_rights_status_check check (
    status in ('pending', 'approved', 'rejected', 'suspended', 'withdrawn', 'revoked')
  ),
  constraint artist_rights_required_confirmations check (
    owns_sound_recordings
    and controls_compositions
    and cleared_contributors
    and cleared_samples
    and cleared_artwork
    and original_catalog_only
    and grant_confirmed
    and dmca_confirmed
    and accurate_information_confirmed
  )
);

create unique index if not exists artist_rights_one_open_application_uidx
  on jukebox.artist_rights_agreements (user_id, artist_id)
  where status in ('pending', 'approved', 'suspended');

create index if not exists artist_rights_user_idx
  on jukebox.artist_rights_agreements (user_id, created_at desc);

create index if not exists artist_rights_status_idx
  on jukebox.artist_rights_agreements (status, created_at desc);

create table if not exists jukebox.artist_catalog_tracks (
  id uuid primary key default gen_random_uuid(),
  agreement_id uuid not null references jukebox.artist_rights_agreements(id) on delete cascade,
  track_audio_id uuid not null references jukebox.track_audio(id) on delete cascade,
  track_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  artist_id uuid not null references jukebox.artists(id) on delete restrict,
  master_owner text not null,
  composition_owner text not null,
  writers text,
  publishers text,
  isrc text,
  rights_notes text,
  status text not null default 'pending',
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint artist_catalog_track_status_check check (
    status in ('pending', 'approved', 'rejected', 'suspended', 'withdrawn')
  ),
  unique (agreement_id, track_audio_id)
);

create index if not exists artist_catalog_track_public_idx
  on jukebox.artist_catalog_tracks (track_id)
  where status = 'approved';

create index if not exists artist_catalog_track_user_idx
  on jukebox.artist_catalog_tracks (user_id, created_at desc);

create table if not exists jukebox.artist_rights_events (
  id bigint generated by default as identity primary key,
  agreement_id uuid not null references jukebox.artist_rights_agreements(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  event_type text not null,
  from_status text,
  to_status text,
  note text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists artist_rights_events_agreement_idx
  on jukebox.artist_rights_events (agreement_id, created_at desc);

create table if not exists jukebox.copyright_notices (
  id uuid primary key default gen_random_uuid(),
  reference_code text not null unique default (
    'SJ-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
  ),
  notice_type text not null default 'takedown',
  claimant_name text not null,
  claimant_organization text,
  claimant_email text not null,
  claimant_phone text not null,
  claimant_address text not null,
  copyrighted_work_description text not null,
  material_location text not null,
  target_track_id text,
  good_faith_confirmed boolean not null,
  accuracy_confirmed boolean not null,
  jurisdiction_confirmed boolean not null default false,
  service_accepted boolean not null default false,
  signature_name text not null,
  parent_notice_id uuid references jukebox.copyright_notices(id) on delete set null,
  status text not null default 'received',
  submitted_ip inet,
  submitted_user_agent text,
  target_user_id uuid references auth.users(id) on delete set null,
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  actioned_at timestamptz,
  subscriber_notified_at timestamptz,
  counter_forwarded_at timestamptz,
  restore_eligible_at timestamptz,
  court_action_received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint copyright_notice_type_check check (notice_type in ('takedown', 'counter_notice')),
  constraint copyright_notice_status_check check (
    status in ('received', 'needs_information', 'actioned', 'rejected', 'countered', 'restored', 'closed')
  ),
  constraint copyright_notice_attestations_check check (
    good_faith_confirmed and accuracy_confirmed
    and (
      notice_type = 'takedown'
      or (jurisdiction_confirmed and service_accepted and parent_notice_id is not null)
    )
  )
);

create index if not exists copyright_notices_status_idx
  on jukebox.copyright_notices (status, created_at desc);

create index if not exists copyright_notices_track_idx
  on jukebox.copyright_notices (target_track_id)
  where target_track_id is not null;

create table if not exists jukebox.copyright_account_actions (
  id uuid primary key default gen_random_uuid(),
  notice_id uuid references jukebox.copyright_notices(id) on delete set null,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null,
  reason text not null,
  active boolean not null default true,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  created_at timestamptz not null default now(),
  reversed_at timestamptz,
  constraint copyright_account_action_type_check check (
    action_type in ('warning', 'strike', 'restriction', 'termination', 'reinstatement')
  )
);

create index if not exists copyright_account_actions_user_idx
  on jukebox.copyright_account_actions (target_user_id, active, created_at desc);

alter table jukebox.artist_rights_agreements enable row level security;
alter table jukebox.artist_catalog_tracks enable row level security;
alter table jukebox.artist_rights_events enable row level security;
alter table jukebox.copyright_notices enable row level security;
alter table jukebox.copyright_account_actions enable row level security;

revoke all on table jukebox.artist_rights_agreements from public, anon, authenticated;
revoke all on table jukebox.artist_catalog_tracks from public, anon, authenticated;
revoke all on table jukebox.artist_rights_events from public, anon, authenticated;
revoke all on table jukebox.copyright_notices from public, anon, authenticated;
revoke all on table jukebox.copyright_account_actions from public, anon, authenticated;

grant select, insert, update, delete on table jukebox.artist_rights_agreements to service_role;
grant select, insert, update, delete on table jukebox.artist_catalog_tracks to service_role;
grant select, insert, update, delete on table jukebox.artist_rights_events to service_role;
grant usage, select on sequence jukebox.artist_rights_events_id_seq to service_role;
grant select, insert, update, delete on table jukebox.copyright_notices to service_role;
grant select, insert, update, delete on table jukebox.copyright_account_actions to service_role;

comment on table jukebox.artist_rights_agreements is
  'Versioned electronic catalog licenses submitted by verified accounts; service-only access.';
comment on table jukebox.artist_catalog_tracks is
  'Private user audio explicitly proposed and approved for public artist discovery.';
comment on table jukebox.copyright_notices is
  'DMCA takedown and counter-notice intake with immutable claimant attestations.';

-- A Supabase auth ban prevents future sessions but an already-issued JWT can
-- remain valid until expiry. Put the repeat-infringer decision in the RLS path
-- as well so termination takes effect immediately for private audio access.
create schema if not exists sj_private;
revoke all on schema sj_private from public, anon;
grant usage on schema sj_private to authenticated, service_role;

create or replace function sj_private.copyright_account_allowed(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select not exists (
    select 1
    from jukebox.copyright_account_actions action
    where action.target_user_id = p_user_id
      and action.action_type = 'termination'
      and action.active
  );
$function$;

revoke all on function sj_private.copyright_account_allowed(uuid) from public, anon;
grant execute on function sj_private.copyright_account_allowed(uuid) to authenticated, service_role;

drop policy if exists track_audio_select_own on jukebox.track_audio;
drop policy if exists track_audio_insert_own_private on jukebox.track_audio;
drop policy if exists track_audio_update_own_private on jukebox.track_audio;
drop policy if exists track_audio_delete_own on jukebox.track_audio;

create policy track_audio_select_own
on jukebox.track_audio
for select
to authenticated
using (
  (select auth.uid()) = uploaded_by
  and sj_private.copyright_account_allowed((select auth.uid()))
);

create policy track_audio_insert_own_private
on jukebox.track_audio
for insert
to authenticated
with check (
  (select auth.uid()) = uploaded_by
  and is_public = false
  and sj_private.copyright_account_allowed((select auth.uid()))
);

create policy track_audio_update_own_private
on jukebox.track_audio
for update
to authenticated
using (
  (select auth.uid()) = uploaded_by
  and sj_private.copyright_account_allowed((select auth.uid()))
)
with check (
  (select auth.uid()) = uploaded_by
  and is_public = false
  and sj_private.copyright_account_allowed((select auth.uid()))
);

-- Retain owner deletion so a terminated user can still request or perform data
-- erasure; SELECT/playback and all new writes remain blocked.
create policy track_audio_delete_own
on jukebox.track_audio
for delete
to authenticated
using ((select auth.uid()) = uploaded_by);

drop policy if exists "jukebox audio read own" on storage.objects;
drop policy if exists "jukebox audio upload own folder" on storage.objects;
drop policy if exists "jukebox audio delete own" on storage.objects;

create policy "jukebox audio read own"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'jukebox-audio'
  and owner_id = (select auth.uid()::text)
  and sj_private.copyright_account_allowed((select auth.uid()))
);

create policy "jukebox audio upload own folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'jukebox-audio'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
  and sj_private.copyright_account_allowed((select auth.uid()))
);

create policy "jukebox audio delete own"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'jukebox-audio'
  and owner_id = (select auth.uid()::text)
);
